# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.1
    hooks:
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "src/requirements.txt"]
      args: ["-f", "requirements.txt", "-o", "src/requirements-test-only.txt", "--only=test"]
