name: black

on: [push, pull_request]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Branch checkout
        uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Black installation
        run: pip install -U black
      - name: Sources linting
        run: black --check .
