autoencoder:
  lr: 0.01
  maxnepochs: 666 # TODO
  batch_size: 128
  max_steps: 32
  num_workers: 0

  
classifier:
  lr: 0.01
  maxnepochs: 666 # TODO
  batch_size: 128
  max_steps: 32
  torch_jit_serialization_method: 'trace'
  num_workers: 0
